# Generated by Django 4.0.2 on 2022-02-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_rename_categoria_categoria_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome',
            new_name='campo',
        ),
    ]
